# Generated by Django 6.1 on 2026-08-12 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_id', models.BooleanField(default=True)),
                ('visitor_photo', models.BooleanField(default=False)),
                ('host_notification', models.BooleanField(default=True)),
                ('incident_notifications', models.BooleanField(default=True)),
                ('visitor_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('session_timeout', models.PositiveIntegerField(default=30)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
