# Generated by Django 6.1 on 2026-08-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_organization_admin_staff_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User setting', 'verbose_name_plural': 'User settings'},
        ),
    ]
