# Generated by Django 6.1 on 2026-08-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=150)),
                ('expected_time', models.DateTimeField(blank=True, null=True)),
                ('visitor_type', models.CharField(choices=[('Guest', 'Guest'), ('Vendor', 'Vendor'), ('Contractor', 'Contractor'), ('Interview', 'Interview'), ('Other', 'Other')], default='Guest', max_length=30)),
                ('status', models.CharField(choices=[('Expected', 'Expected'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('Cancelled', 'Cancelled')], default='Expected', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
