# Generated by Django 6.1 on 2026-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('Guest', 'Guest'), ('Vendor', 'Vendor'), ('Contractor', 'Contractor'), ('Interview', 'Interview'), ('Delivery', 'Delivery')], default='Guest', max_length=30),
        ),
    ]
