# Generated by Django 6.1 on 2026-08-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_visitor_visitor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='location',
            field=models.CharField(default='Main Reception', max_length=255),
        ),
    ]
