function pdfText(value) {
    return String(value ?? "")
        .normalize("NFKD")
        .replace(/[^\x20-\x7E]/g, "")
        .replace(/\\/g, "\\\\")
        .replace(/\(/g, "\\(")
        .replace(/\)/g, "\\)");
}

function text(x, y, size, value, color = "0.10 0.15 0.23") {
    return `${color} rg BT /F1 ${size} Tf ${x} ${y} Td (${pdfText(value)}) Tj ET`;
}

function metricCard(x, y, width, label, value, accent) {
    return [
        `0.96 0.97 0.99 rg ${x} ${y} ${width} 72 re f`,
        `${accent} rg ${x} ${y} 5 72 re f`,
        text(x + 18, y + 46, 9, label.toUpperCase(), "0.43 0.49 0.58"),
        text(x + 18, y + 19, 22, value)
    ].join("\n");
}

function sectionRow(y, label, value) {
    return [
        `0.88 0.90 0.94 RG 50 ${y - 8} m 562 ${y - 8} l S`,
        text(55, y, 10, label, "0.35 0.40 0.48"),
        text(490, y, 11, value)
    ].join("\n");
}

export function buildReportPdf(reportData, dateFrom, dateTo) {
    const visitors = reportData?.visitors || {};
    const incidents = reportData?.incidents || {};
    const generatedAt = new Date().toLocaleString("en-GB", {
        dateStyle: "medium",
        timeStyle: "short"
    });

    const stream = [
        "0.04 0.12 0.23 rg 0 680 612 112 re f",
        text(48, 744, 25, "SmartEntry", "1 1 1"),
        text(48, 716, 14, "Visitor and Incident Report", "0.74 0.82 0.92"),
        text(430, 744, 9, "REPORT PERIOD", "0.74 0.82 0.92"),
        text(430, 726, 10, `${dateFrom} to ${dateTo}`, "1 1 1"),
        text(48, 650, 10, "EXECUTIVE SUMMARY", "0.15 0.39 0.92"),
        text(48, 626, 15, "Activity at a glance"),
        metricCard(48, 528, 244, "Total visitors", visitors.total || 0, "0.15 0.39 0.92"),
        metricCard(320, 528, 244, "Total incidents", incidents.total || 0, "0.86 0.15 0.15"),
        text(48, 488, 10, "VISITOR STATISTICS", "0.15 0.39 0.92"),
        sectionRow(458, "Checked in", visitors.checkedIn || 0),
        sectionRow(426, "Checked out", visitors.checkedOut || 0),
        sectionRow(394, "Expected", visitors.expected || 0),
        text(48, 348, 10, "INCIDENT STATISTICS", "0.86 0.15 0.15"),
        sectionRow(318, "Open incidents", incidents.open || 0),
        sectionRow(286, "Resolved incidents", incidents.resolved || 0),
        sectionRow(254, "High-priority incidents", incidents.highPriority || 0),
        `0.94 0.96 0.99 rg 48 158 516 58 re f`,
        text(62, 191, 9, "SUMMARY", "0.43 0.49 0.58"),
        text(62, 172, 10, `${visitors.total || 0} visitor(s) and ${incidents.total || 0} incident(s) were recorded during this period.`),
        text(48, 58, 8, `Generated by SmartEntry on ${generatedAt}`, "0.52 0.57 0.65"),
        text(518, 58, 8, "Page 1 of 1", "0.52 0.57 0.65")
    ].join("\n");

    const objects = [
        "<< /Type /Catalog /Pages 2 0 R >>",
        "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
        `<< /Title (SmartEntry Report) /Author (SmartEntry) /Subject (Report for ${pdfText(dateFrom)} to ${pdfText(dateTo)}) >>`
    ];

    let pdf = "%PDF-1.4\n";
    const offsets = [0];
    objects.forEach((object, index) => {
        offsets.push(pdf.length);
        pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
    });
    const xrefOffset = pdf.length;
    pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
    offsets.slice(1).forEach((offset) => {
        pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
    });
    pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R /Info 6 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

    return new TextEncoder().encode(pdf);
}

export function downloadReportPdf(reportData, dateFrom, dateTo) {
    const bytes = buildReportPdf(reportData, dateFrom, dateTo);
    const blob = new Blob([bytes], { type: "application/pdf" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `smartentry-report-${dateFrom}-to-${dateTo}.pdf`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
}
